### ISSUE TITLE
Would like to connect with you on some of the pointers finding

### ISSUE THREAD

**Issue by bbsxjy** [gitjunkail/Crimson-Desert#1]
Hey @gitjunkail ,

This project is very inspiring and helpful. I really learnt a lot from it. I'm using current existed framework and implemented usable bot already. Just have few questions regarding how to find some pointers, e.g. looting base, bag list etc.

Hope you will read about this issue. I would like to connect with you either through discord or other message tools to gain some help and learn more from you.

Please add me @Discord: Ashinata#5958 

Thanks in advance!

J

**Comment by jsoctocat** [comment]
sorry, I won't be able to help you on this matter, this project is uploaded AS IS. I purposely deleted the addresses so that others will only be able to study the coding structure.
